export const realValues = {data:[
    {
      totalArea:570.7,
       companyName:'Прайм'
    },
    {
      totalArea:216,
       companyName:'Чорна'
    },
    {
      totalArea:53.5,
       companyName:'Олімп'
    },
    {
      totalArea:109.2,
       companyName:'Крістіна'
    },
    {
      totalArea:110,
       companyName:'Бізон'
    },
    {
      totalArea:67,
       companyName:'Шишка'
    },
    {
      totalArea:33.9,
       companyName:'Ігор'
    },
    {
      totalArea:124,
       companyName:'Спейс хаб'
    },
    {
      totalArea:353.35,
       companyName:'Пантера'
    },
    {
      totalArea:214.3,
       companyName:'Шептієва'
    }
  ]}