name: Run Playwright Tests

on:
  push:
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build the application
        run: yarn build

      - name: Start the application
        run: yarn devv &
        env:
          PORT: 3000

      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:3000

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
