name: Run Playwright Tests

on:
  push:
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run app
        run: yarn devv

      - name: Run Playwright tests
        run: npx playwright test
